# Change these first
owner: UnivTerbuka # Your GitHub username
repo: online # Your Github repository name

# Add your sites here
sites:
  - name: Universitas Terbuka - Making Higher Education Open To All
    url: https://www.ut.ac.id/
  - name: Sistem Informasi Akademik UT
    url: https://sia.ut.ac.id/
  - name: E-learning Universitas Terbuka
    url: https://elearning.ut.ac.id/
  - name: Mahasiswa UT - Making Higher Education Open To All
    url: https://mahasiswa.ut.ac.id/
  - name: APLIKASI TUGAS MATA KULIAH
    url: https://tmk.ut.ac.id/tmkui/#/
    expectedStatusCodes:
      - 200
      - 301
      - 302
  - name: Layanan Informasi dan Bantuan - UNIVERSITAS TERBUKA
    url: http://hallo-ut.ut.ac.id/
  - name: Perpustakaan UT - Digital Library of A Cyber University of Indonesia
    url: https://www.pustaka.ut.ac.id/
    expectedStatusCodes:
      - 200
      - 302
  - name: Lembaga Penelitian dan Pengabdian Pada Masyarakat (LPPM) - UT
    url: http://lppm.ut.ac.id/
  - name: Program Sertifikat Terbuka Online
    url: http://moocs.ut.ac.id/
  - name: UT RADIO
    url: http://utradio.ut.ac.id/
  - name: Tracer Studi Universitas Terbuka
    url: http://tracer.lppm.ut.ac.id/
  - name: Sistem Unggah Karil PROGRAM PGPAUD DAN PGSD (Pendas)
    url: http://karil.ut.ac.id/pendas/
    expectedStatusCodes:
      - 200
      - 301
      - 302
  - name: Sistem Unggah Karil PROGRAM FE, FHISIP, FMIPA, FKIP (Non Pendas)
    url: http://karil.ut.ac.id/nonpendas/
    expectedStatusCodes:
      - 200
      - 301
      - 302
  - name: Situs Web Berbagi Ilmu oleh Staff Universitas Terbuka
    url: http://staff.ut.ac.id/
  - name: Universitas Terbuka Repository
    url: http://repository.ut.ac.id/
  - name: Promise UT
    url: https://promise.ut.ac.id/

status-website:
  name: Status Web Universitas Terbuka
  baseUrl: /online
  logoUrl: https://www.ut.ac.id/images/logo-ut-small-transparent.png
  introTitle: "**Universitas Terbuka (UT)** adalah Perguruan Tinggi Negeri ke-45 di Indonesia yang diresmikan pada tanggal 4 September 1984, berdasarkan Keputusan Presiden RI Nomor 41 Tahun 1984."
  introMessage: Halaman ini berfungsi untuk memonitor website yang dimiliki Universitas Terbuka
  navbar:
    - title: Status
      href: /
    - title: Github
      href: https://github.com/$OWNER/$REPO

i18n:
  activeIncidents: Insiden Aktif
  allSystemsOperational: Semua sistem beroperasi
  incidentReport: "Laporan insiden #$NUMBER →"
  activeIncidentSummary: Dibuka pada $DATE dengan $POSTS postingan
  incidentTitle: Detail Insiden $NUMBER
  incidentDetails: Detail Insiden
  incidentFixed: Diperbaiki
  incidentOngoing: Sedang berlangsung
  incidentOpenedAt: Dibuka pada
  incidentClosedAt: Ditutup pada
  incidentSubscribe: Berlangganan Pembaruan
  incidentViewOnGitHub: Lihat di GitHub
  incidentCommentSummary: Diposting pada $DATE oleh $AUTHOR
  incidentBack: ← Kembali ke semua insiden
  pastIncidents: Insiden Masa Lalu
  pastIncidentsResolved: Diselesaikan dalam $MINUTES menit dengan $POSTS postingan
  liveStatus: Status Langsung
  overallUptime: Uptime keseluruhan $UPTIME%
  overallUptimeTitle: Uptime keseluruhan
  averageResponseTime: Waktu respons rata-rata $TIMEms
  averageResponseTimeTitle: Respon rata-rata
  sevelDayResponseTime: Waktu respons 7 hari
  responseTimeMs: Waktu respons (ms)
  up: Aktif
  down: Non-aktif
  ms: ms
  loading: Loading
  navGitHub: GitHub
  footer: Halaman ini [open source]($REPO), dikembangkan oleh [Habib Rohman](https://github.com/hexatester) dengan menggunakan [Upptime](https://upptime.js.org)
  rateLimitExceededTitle: Batas tarif terlampaui
  rateLimitExceededIntro: Anda telah melebihi jumlah permintaan yang dapat Anda lakukan dalam satu jam, jadi Anda harus menunggu sebelum mengakses situs web ini lagi. Sebagai alternatif, Anda dapat menambahkan Token Akses Pribadi GitHub untuk terus menggunakan situs web ini.
  rateLimitExceededWhatDoesErrorMean: Apa arti kesalahan ini?
  rateLimitExceededErrorMeaning: Situs web ini menggunakan API GitHub untuk mengakses data waktu nyata tentang status situs web kami. Secara default, GitHub mengizinkan setiap alamat IP 60 permintaan per jam, yang telah Anda gunakan.
  rateLimitExceededErrorHowCanFix: Bagaimana cara memperbaikinya?
  rateLimitExceededErrorFix: Anda dapat menunggu satu jam lagi dan batas alamat IP Anda akan dipulihkan. Sebagai alternatif, Anda dapat menambahkan Token Akses Pribadi GitHub Anda, yang memberi Anda 5.000 permintaan tambahan per jam.
  rateLimitExceededGeneratePAT: Pelajari cara membuat Token Akses Pribadi
  rateLimitExceededHasSet: Anda memiliki set token akses pribadi.
  rateLimitExceededRemoveToken: Hapus token
  rateLimitExceededGitHubPAT: Token Akses Pribadi GitHub
  rateLimitExceededCopyPastePAT: Salin dan tempel token Anda
  rateLimitExceededSaveToken: Simpan token
  errorTitle: Terjadi kesalahan
  errorIntro: Terjadi kesalahan saat mencoba mendapatkan detail status terbaru.
  errorText: Anda dapat mencoba lagi dalam beberapa saat.
  errorHome: Buka beranda
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
